### ISSUE TITLE
It'd be awesome to have a Homebrew package for this

### ISSUE THREAD

**Issue by simonexmachina** [ltratt/multitime#19]
Thanks!

**Comment by ltratt** [comment]
If someone wants to provide one, I'd be willing to merge the bits necessary, but it will require someone with OS X knowledge (and, indeed, an OS X machine!) to do so.

**Comment by ltratt** [comment]
Closing because this will take someone Homebrew-wise to cook up and isn't really an issue with multitime itself.

**Comment by asfaltboy** [comment]
Someone seems to have created this tap here: https://github.com/Tenzer/homebrew-tap/blob/master/multitime.rb

Can be installed via:

```
brew install Tenzer/tap/multitime
```

Not sure what are @ltratt 's feelings on adding this to the docs / README or to the https://tratt.net/laurie/src/multitime/releases.html page

**Comment by ltratt** [comment]
Thanks I've added this to the releases page at the URL above!
