### ISSUE TITLE
Segmentation fault on OSX when running without '-f liketime'

### ISSUE THREAD

**Issue by zbentley** [ltratt/multitime#22]
### Environment

OSX 10.13.4.

Apple LLVM version 9.1.0 (clang-902.0.39.1)
Target: x86_64-apple-darwin17.5.0
Thread model: posix

autoconf (GNU Autoconf) 2.69

### Observed behavior

On OSX, any output format option other than `liketime` segfaults after running the command the specified number of times.

```bash
#> multitime -f rusage -n 2 sleep 1
===> multitime results
Segmentation fault: 11
```

```bash
#> multitime -n 2 sleep 1
===> multitime results
Segmentation fault: 11
```

`liketime` works fine though:

```bash
#> multitime -f liketime -n 2 sleep 1
real         1.00
user         0.00
sys          0.00
```

### Expected behavior

No segfaults.

**Comment by ltratt** [comment]
Unfortunately I don't have an OS X machine to try this on, so to have any chance of fixing this, I'm going to need help. Can you run `gdb` to find out where it's segfaulting, for example?

**Comment by zbentley** [comment]
I'll do that, but it's my first time using the GDB toolset for debugging, so I apologize if it takes me a bit to learn and I don't get back to you for a few days ($day_job and all that). I'll be sure to follow up, though. Thanks for responding!
