### ISSUE TITLE
Release version 1.5

### ISSUE THREAD

**Issue by kirelagin** [ltratt/multitime#25]
#23 fixes a segfault, so it seems to be worth a new release. What’s even worse, the 1.4 release is tagged on some weird branch completely separate from master, so the patch from #23 does not apply to it.

Master has all changes from 1.4 except for an entry in `HISTORY` and two contributors in `CREDITS`.

**Comment by ltratt** [comment]
Yes, this is a mess. The problem is that the code on master isn't finished and I lack the time and motivation to do so. It really requires someone taking on the mantle to tidy this up -- I'll happily support anyone who's willing to put in the time!

**Comment by kirelagin** [comment]
Ah, ok, got it. At least, apparently, there is no segfault in 1.4 :).
