### ISSUE TITLE
Brew formula not working

### ISSUE THREAD

**Issue by oliversheridanmethven** [ltratt/multitime#30]
Running `brew install Tenzer/tap/multitime` as per the download instructions gives:
```
==> Tapping tenzer/tap
Cloning into '/usr/local/Homebrew/Library/Taps/tenzer/homebrew-tap'...
remote: Enumerating objects: 186, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 186 (delta 0), reused 0 (delta 0), pack-reused 185
Receiving objects: 100% (186/186), 26.41 KiB | 6.60 MiB/s, done.
Resolving deltas: 100% (61/61), done.
Tapped 5 formulae (20 files, 44.9KB).
Warning: No available formula or cask with the name "tenzer/tap/multitime". Did you mean tenzer/tap/quirky?
```

**Comment by ltratt** [comment]
I don't have an OS X machine, so someone would need to tell me what the right incantation is -- if they do, I'll update the instructions ASAP!

**Comment by snim2** [comment]
@oliversheridanmethven The relevant tap is now in `homebrew-core` here: https://github.com/Homebrew/homebrew-core/blob/master/Formula/m/multitime.rb so you need to run `brew install multitime`, which works OK for me BTW.

**Comment by ltratt** [comment]
Thanks @snim2! [And very good to see you, albeit virtually :)]
